const SYMBOLS = ['BTC-USD','ETH-USD','SOL-USD','XRP-USD','ADA-USD','DOGE-USD','LINK-USD','AVAX-USD'];
const API = 'https://api.exchange.coinbase.com';
const STORAGE_KEY = 'sunnyTradeMobileV02';
let currentMarket = {};
let state = loadState();

function defaultState(){return {cash:1000,startingBalance:1000,maxTrade:100,feePct:.10,slippagePct:.05,positions:[],history:[],mode:'live'};}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return defaultState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updatePortfolio();}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0))}
function nfmt(n,d=2){return Number(n).toLocaleString('en-US',{maximumFractionDigits:d})}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function ema(values,period){const k=2/(period+1);let e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function rsi(values,p=14){if(values.length<p+1)return 50;let g=0,l=0;for(let i=values.length-p;i<values.length;i++){const d=values[i]-values[i-1];d>0?g+=d:l-=d}if(l===0)return 100;const rs=(g/p)/(l/p);return 100-(100/(1+rs))}
function atr(c,p=14){if(c.length<p+1)return 0;let trs=[];for(let i=1;i<c.length;i++){const h=+c[i][2],lo=+c[i][1],pc=+c[i-1][4];trs.push(Math.max(h-lo,Math.abs(h-pc),Math.abs(lo-pc)))}return trs.slice(-p).reduce((a,b)=>a+b,0)/p}
function analyze(candles){const sorted=[...candles].sort((a,b)=>a[0]-b[0]);const closes=sorted.map(x=>+x[4]);const vols=sorted.map(x=>+x[5]);const price=closes.at(-1), prev=closes.at(-2)||price;const e20=ema(closes.slice(-60),20),e50=ema(closes.slice(-100),50);const fast=ema(closes.slice(-50),12),slow=ema(closes.slice(-70),26);const macd=fast-slow;const rr=rsi(closes,14);const a=atr(sorted,14);const avgVol=vols.slice(-21,-1).reduce((x,y)=>x+y,0)/Math.max(1,vols.slice(-21,-1).length);const vr=(vols.at(-1)||0)/(avgVol||1);let score=0;const reasons=[];
 if(price>e20){score++;reasons.push('قیمت بالای EMA20 است')} else {score--;reasons.push('قیمت زیر EMA20 است')}
 if(e20>e50){score++;reasons.push('روند میان‌مدت مثبت است')} else score--;
 if(rr>=45&&rr<=68){score++;reasons.push('RSI در محدوده متعادل است')} if(rr>75){score-=2;reasons.push('RSI بیش‌خرید را نشان می‌دهد')} if(rr<35){score--;reasons.push('RSI ضعیف است')}
 if(macd>0)score++; else score--;
 if(vr>1.15){score++;reasons.push('حجم بالاتر از میانگین است')}
 const volPct=a/price*100;if(volPct>6){score--;reasons.push('نوسان بسیار بالاست')}
 const signal=score>=3?'BUY':score<=-2?'AVOID':'WAIT';
 return {price,change:(price-prev)/prev*100,ema20:e20,ema50:e50,rsi:rr,macd,atrPct:volPct,volRatio:vr,score,signal,reasons:reasons.slice(0,3)};
}
async function fetchCandles(symbol){const url=`${API}/products/${symbol}/candles?granularity=3600`;const r=await fetch(url,{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data)||data.length<30)throw new Error('داده کافی نیست');return data;}
function makeDemoCandles(symbol){let base={ 'BTC-USD':62000,'ETH-USD':2800,'SOL-USD':145,'XRP-USD':.58,'ADA-USD':.36,'DOGE-USD':.11,'LINK-USD':13,'AVAX-USD':27}[symbol]||100;let arr=[];for(let i=0;i<120;i++){const wave=Math.sin(i/8)*.012+Math.sin(i/21)*.02;const trend=i*.00032;const close=base*(1+trend+wave);const open=close*(1-Math.sin(i)*.003);const hi=Math.max(open,close)*1.006;const lo=Math.min(open,close)*.994;const vol=1000*(1+Math.abs(Math.sin(i/6)));arr.push([Date.now()/1000-(120-i)*3600,lo,hi,open,close,vol])}return arr;}
async function scan(){const grid=document.getElementById('marketGrid');grid.innerHTML='<div class="empty">در حال دریافت و تحلیل اطلاعات بازار…</div>';document.getElementById('statusLine').textContent='در حال به‌روزرسانی…';currentMarket={};let liveCount=0;
 const results=await Promise.all(SYMBOLS.map(async symbol=>{try{const c=await fetchCandles(symbol);liveCount++;return [symbol,analyze(c),true]}catch(e){return [symbol,analyze(makeDemoCandles(symbol)),false]}}));
 results.forEach(([s,a,live])=>currentMarket[s]={...a,live});state.mode=liveCount===SYMBOLS.length?'live':liveCount?'mixed':'demo';save();renderMarkets();document.getElementById('statusLine').textContent=`آخرین اسکن: ${new Date().toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}`;if(liveCount<SYMBOLS.length)toast(`داده زنده ${liveCount}/${SYMBOLS.length} بازار؛ بقیه Demo`);checkStops();}
function renderMarkets(){const grid=document.getElementById('marketGrid');grid.innerHTML='';Object.entries(currentMarket).forEach(([s,a])=>{const badge=a.signal==='BUY'?['بررسی خرید','signal-buy']:a.signal==='AVOID'?['ریسک بالا','signal-avoid']:['صبر','signal-wait'];const div=document.createElement('article');div.className='market card';div.innerHTML=`<div class="market-head"><div><div class="symbol">${s}</div><div class="small">${a.live?'داده عمومی Live':'Demo fallback'}</div></div><div><div class="price">${money(a.price)}</div><div class="change ${a.change>=0?'good':'bad'}">${a.change>=0?'+':''}${nfmt(a.change)}%</div></div></div><div class="metrics"><div class="metric"><span>RSI</span><b>${nfmt(a.rsi,1)}</b></div><div class="metric"><span>ATR%</span><b>${nfmt(a.atrPct,1)}</b></div><div class="metric"><span>Volume</span><b>${nfmt(a.volRatio,1)}×</b></div><div class="metric"><span>Score</span><b>${a.score}</b></div></div><div class="signal"><span class="signal-badge ${badge[1]}">${badge[0]}</span><button class="secondary trade-open" data-symbol="${s}" ${a.signal!=='BUY'?'disabled':''}>Paper Buy</button></div><p class="reason">${a.reasons.join(' • ')}</p>`;grid.appendChild(div)});document.querySelectorAll('.trade-open').forEach(b=>b.addEventListener('click',()=>openTrade(b.dataset.symbol)));}
function openTrade(symbol){const a=currentMarket[symbol];if(!a)return;document.getElementById('tradeSymbol').textContent=symbol;document.getElementById('tradeAmount').value=Math.min(20,state.maxTrade);document.getElementById('tradeSummary').innerHTML=`قیمت فعلی: <b class="ltr">${money(a.price)}</b><br>RSI: ${nfmt(a.rsi,1)} • Score: ${a.score}<br>${a.live?'داده عمومی زنده':'⚠️ داده Demo — فقط برای تست رابط'}`;document.getElementById('tradeDialog').showModal();}
function paperBuy(){const symbol=document.getElementById('tradeSymbol').textContent;const a=currentMarket[symbol];let amount=+document.getElementById('tradeAmount').value,stop=+document.getElementById('stopPct').value,take=+document.getElementById('takePct').value;if(!a||amount<5)return toast('مبلغ معتبر وارد کن');amount=Math.min(amount,state.maxTrade,state.cash);if(amount<5)return toast('موجودی کافی نیست');if(state.positions.some(p=>p.symbol===symbol))return toast('برای این بازار معامله باز داری');const slip=state.slippagePct/100,fee=state.feePct/100;const entry=a.price*(1+slip);const feeUsd=amount*fee;const net=amount-feeUsd;const qty=net/entry;state.cash-=amount;state.positions.push({id:crypto.randomUUID?.()||String(Date.now()),symbol,amount,qty,entry,stop:entry*(1-stop/100),take:entry*(1+take/100),openedAt:Date.now(),sourceLive:a.live});save();renderPositions();toast('معامله آزمایشی باز شد');}
function closePosition(id,why='Manual'){const p=state.positions.find(x=>x.id===id);if(!p)return;const a=currentMarket[p.symbol];const rawPrice=a?.price||p.entry;const exit=rawPrice*(1-state.slippagePct/100);const gross=p.qty*exit;const fee=gross*state.feePct/100;const proceeds=gross-fee;const pnl=proceeds-p.amount;state.cash+=proceeds;state.positions=state.positions.filter(x=>x.id!==id);state.history.unshift({...p,exit,closedAt:Date.now(),pnl,why});save();renderPositions();renderHistory();toast(`معامله بسته شد: ${money(pnl)}`)}
function checkStops(){[...state.positions].forEach(p=>{const a=currentMarket[p.symbol];if(!a)return;if(a.price<=p.stop)closePosition(p.id,'Stop Loss');else if(a.price>=p.take)closePosition(p.id,'Take Profit')})}
function renderPositions(){const root=document.getElementById('positionsList');if(!state.positions.length){root.innerHTML='<div class="empty">هیچ معامله آزمایشی بازی نداری.</div>';return}root.innerHTML='';state.positions.forEach(p=>{const price=currentMarket[p.symbol]?.price||p.entry;const est=p.qty*price*(1-state.slippagePct/100);const pnl=est-p.amount;const d=document.createElement('div');d.className='position card';d.innerHTML=`<div class="row"><div><div class="symbol">${p.symbol}</div><div class="small">ورود ${money(p.entry)} • ${p.sourceLive?'Live':'Demo'}</div></div><div class="pnl ${pnl>=0?'good':'bad'}">${money(pnl)}</div></div><div class="metrics"><div class="metric"><span>SL</span><b>${money(p.stop)}</b></div><div class="metric"><span>TP</span><b>${money(p.take)}</b></div><div class="metric"><span>مبلغ</span><b>${money(p.amount)}</b></div><div class="metric"><span>فعلی</span><b>${money(price)}</b></div></div><button class="danger full close-pos" data-id="${p.id}">بستن آزمایشی</button>`;root.appendChild(d)});document.querySelectorAll('.close-pos').forEach(b=>b.onclick=()=>closePosition(b.dataset.id));}
function renderHistory(){const root=document.getElementById('historyList');if(!state.history.length){root.innerHTML='<div class="empty">هنوز معامله بسته‌شده‌ای ثبت نشده.</div>';return}root.innerHTML='';state.history.slice(0,100).forEach(h=>{const d=document.createElement('div');d.className='history-item card';d.innerHTML=`<div class="row"><div><div class="symbol">${h.symbol}</div><div class="small">${h.why} • ${new Date(h.closedAt).toLocaleDateString('fa-IR')}</div></div><div class="pnl ${h.pnl>=0?'good':'bad'}">${money(h.pnl)}</div></div><div class="small ltr" style="margin-top:8px">Entry ${money(h.entry)} → Exit ${money(h.exit)}</div>`;root.appendChild(d)});}
function updatePortfolio(){let open=0;state.positions.forEach(p=>{const price=currentMarket[p.symbol]?.price||p.entry;open+=p.qty*price*(1-state.slippagePct/100)-p.amount});const equity=state.cash+state.positions.reduce((sum,p)=>sum+p.qty*(currentMarket[p.symbol]?.price||p.entry)*(1-state.slippagePct/100),0);document.getElementById('equity').textContent=money(equity);document.getElementById('openPnl').textContent=money(open);document.getElementById('openPnl').className='medium '+(open>=0?'good':'bad');document.getElementById('openCount').textContent=state.positions.length;document.getElementById('dataModeLabel').textContent=state.mode==='live'?'Live':state.mode==='mixed'?'Mixed':'Demo';}
function syncSettings(){document.getElementById('startingBalance').value=state.startingBalance;document.getElementById('maxTrade').value=state.maxTrade;document.getElementById('feePct').value=state.feePct;document.getElementById('slippagePct').value=state.slippagePct;}
document.getElementById('scanBtn').onclick=scan;document.getElementById('refreshBtn').onclick=scan;document.getElementById('confirmPaperBuy').onclick=(e)=>{e.preventDefault();paperBuy();document.getElementById('tradeDialog').close()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active');if(b.dataset.view==='positionsView')renderPositions();if(b.dataset.view==='historyView')renderHistory();});document.getElementById('saveSettings').onclick=()=>{state.startingBalance=+document.getElementById('startingBalance').value||1000;state.maxTrade=+document.getElementById('maxTrade').value||100;state.feePct=+document.getElementById('feePct').value||0;state.slippagePct=+document.getElementById('slippagePct').value||0;save();toast('تنظیمات ذخیره شد')};document.getElementById('resetPaper').onclick=()=>{if(confirm('تمام معاملات و تاریخچه آزمایشی پاک شود؟')){const keep={startingBalance:state.startingBalance,maxTrade:state.maxTrade,feePct:state.feePct,slippagePct:state.slippagePct};state={...defaultState(),...keep,cash:keep.startingBalance};save();renderPositions();renderHistory();toast('Paper Trading ریست شد')}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));syncSettings();renderPositions();renderHistory();updatePortfolio();scan();
