/* Sunny Trade AI v8.0 — algorithmic analysis and local paper trading ONLY. */
'use strict';
const API='https://api.exchange.coinbase.com',KEY='sunnyTradeMobileV02',MAX=100,QUOTE_TTL=120000;
const $=id=>document.getElementById(id), USD=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD'}),num=(n,d=2)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d}),price=n=>Number.isFinite(n)?'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:n<.01?10:n<1?6:2}):'—';
const date=n=>Number.isFinite(n)?new Date(n).toLocaleString('fa-IR'):'—';
const DEFAULT=()=>({cash:1000,startingBalance:1000,maxTrade:100,feePct:.1,slippagePct:.05,positions:[],history:[],mode:'offline'});
let state;try{state={...DEFAULT(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state=DEFAULT()};
if(!Array.isArray(state.positions))state.positions=[];if(!Array.isArray(state.history))state.history=[];
let markets={},quotes={},lastSuccess=0,lastAttempt=0,busy=false,selected='',ranked=[],closing=new Set(),products=[];
const HOUR=3600000,PERIODS=[{sec:60,hold:300,label:'۵ دقیقه',min:95},{sec:300,hold:1200,label:'۲۰ دقیقه',min:95},{sec:900,hold:14400,label:'۴ ساعت',min:95},{sec:3600,hold:86400,label:'۲۴ ساعت',min:95},{sec:86400,hold:2592000,label:'۳۰ روز',min:95}];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3700)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('خطای ذخیره‌سازی؛ نسخه پشتیبان بگیر')}portfolio()}
async function req(url,tries=2){for(let i=0;i<=tries;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{signal:c.signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok){if((r.status===429||r.status>=500)&&i<tries){await wait(900*(i+1));continue}throw Error('HTTP '+r.status)}return await r.json()}catch(e){if(i===tries)throw e;await wait(800*(i+1))}finally{clearTimeout(t)}}}
function cleanSymbol(s){s=String(s).trim().toUpperCase().replace(/-USD$/,'');return /^[A-Z0-9]{2,16}$/.test(s)?s+'-USD':null}
async function candles(s,sec){const raw=await req(`${API}/products/${encodeURIComponent(s)}/candles?granularity=${sec}`,1);if(!Array.isArray(raw))throw Error('قالب کندل نامعتبر');const cutoff=Math.floor(Date.now()/1000/sec)*sec;const rows=raw.filter(r=>Array.isArray(r)&&r.length>=6&&r.slice(0,6).every(x=>Number.isFinite(Number(x)))&&Number(r[0])<cutoff).map(r=>r.slice(0,6).map(Number)).filter(r=>r[1]>0&&r[2]>=r[1]&&r[3]>=r[1]&&r[3]<=r[2]&&r[4]>=r[1]&&r[4]<=r[2]&&r[5]>=0).sort((a,b)=>a[0]-b[0]).filter((r,i,a)=>!i||r[0]!==a[i-1][0]).slice(-280);if(rows.length<95)throw Error('کمبود کندل');if(Date.now()/1000-rows.at(-1)[0]>sec*5)throw Error('کندل قدیمی');return rows}
function ema(x,n){let v=x.slice(0,n).reduce((a,b)=>a+b,0)/n;for(let i=n;i<x.length;i++)v+=(x[i]-v)*2/(n+1);return v}
function rsi(x,n=14){let g=0,l=0;for(let i=1;i<=n;i++){let d=x[i]-x[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=n;l/=n;for(let i=n+1;i<x.length;i++){let d=x[i]-x[i-1];g=(g*13+Math.max(0,d))/14;l=(l*13+Math.max(0,-d))/14}return l===0?(g===0?50:100):100-100/(1+g/l)}
function atr(a){const t=[];for(let i=1;i<a.length;i++){const p=a[i-1][4];t.push(Math.max(a[i][2]-a[i][1],Math.abs(a[i][2]-p),Math.abs(a[i][1]-p)))}let v=t.slice(0,14).reduce((a,b)=>a+b,0)/14;for(let i=14;i<t.length;i++)v=(v*13+t[i])/14;return v}
function analyze(a,sec){const x=a.map(r=>r[4]),vol=a.map(r=>r[5]),p=x.at(-1),e20=ema(x,20),e50=ema(x,50),r=rsi(x),atrPct=atr(a)/p*100,v20=vol.slice(-21,-1).reduce((b,v)=>b+v,0)/20,vr=v20>0?vol.at(-1)/v20:0,macd=ema(x,12)-ema(x,26),rise=p/x.at(-2)-1;let score=0,why=[];
if(p>e20){score+=2;why.push('قیمت بالای میانگین ۲۰')}else{score-=2;why.push('قیمت زیر میانگین ۲۰')}
if(e20>e50){score+=2;why.push('روند میان‌مدت صعودی')}else{score-=2;why.push('روند میان‌مدت ضعیف')}
if(r>=43&&r<=66){score+=2;why.push('RSI متعادل')}else if(r>74){score-=2;why.push('RSI بیش‌خرید')}else if(r<34){score-=2;why.push('RSI ضعیف')}
if(macd>0)score++;else score--;
if(vr>1.15){score++;why.push('حجم بالاتر از میانگین')}
if(atrPct>6){score-=2;why.push('نوسان شدید')}
const dollars=a.slice(-20).reduce((sum,row)=>sum+row[4]*row[5],0)/20*86400/sec;
const valid=[score,r,atrPct,vr,p,dollars].every(Number.isFinite)&&atrPct>0;
const eligible=valid&&score>=5&&r<72&&atrPct<=6&&dollars>=200000;
const stopPct=Math.min(8,Math.max(.4,atrPct*1.5)),takePct=Math.min(18,Math.max(.8,stopPct*1.8));
return {sec,price:p,updated:Date.now(),candles:a,score,rsi:r,atrPct,vr,change:rise*100,volumeUsd:dollars,reasons:why,eligible,status:!valid?'DATA':eligible?'BUY':score<=-2?'AVOID':'WAIT',stopPct,takePct,risk:atrPct>3?'زیاد':atrPct>1.4?'متوسط':'کمتر'}
}
const MIN_NET_RR=1.5;
// Reject a candidate if estimated round-trip trading costs make the net reward/risk inadequate.
// This is a deterministic filter, NOT a probability or profit forecast.
function quality(a,amount=20){
 if(!a||!a.eligible||!Number.isFinite(a.price)||a.price<=0)return null;
 if(![amount,state.feePct,state.slippagePct].every(Number.isFinite)||amount<5)return null;
 const out=scenario(amount,a.price,a.stopPct,a.takePct);
 if(!out||!Number.isFinite(out.up)||!Number.isFinite(out.down)||out.up<=0||out.down>=0)return null;
 const rr=out.up/-out.down;
 if(!Number.isFinite(rr)||rr<MIN_NET_RR)return null;
 return {...out,rr};
}
function choose(a){const arr=Object.values(a.periods||{}).filter(x=>quality(x)).sort((a,b)=>quality(b).rr-quality(a).rr||b.score-a.score||a.atrPct-b.atrPct);return arr[0]||null}
function bestSignal(s){return choose(markets[s]||{})}
function scenario(a,p,sl,tp){const f=Number(state.feePct)/100,v=Number(state.slippagePct)/100,entry=p*(1+v),qty=a*(1-f)/entry;const get=x=>qty*x*(1-v)*(1-f);return {up:get(entry*(1+tp/100))-a,down:get(entry*(1-sl/100))-a}}
function quoteOK(s){return quotes[s]&&Number.isFinite(quotes[s].value)&&quotes[s].value>0&&Date.now()-quotes[s].received<QUOTE_TTL}
async function quote(s){const q=await req(`${API}/products/${encodeURIComponent(s)}/ticker`,1),v=Number(q.price),exchange=Date.parse(q.time||'');if(!Number.isFinite(v)||v<=0)throw Error('قیمت نامعتبر');if(Number.isFinite(exchange)&&Math.abs(Date.now()-exchange)>180000)throw Error('زمان قیمت نامعتبر');quotes[s]={value:v,received:Date.now(),exchange:Number.isFinite(exchange)?exchange:null};return quotes[s]}
function portfolio(){let eq=state.cash,pnl=0,missing=false;for(const p of state.positions){if(!quoteOK(p.symbol)){missing=true;continue}const val=p.qty*quotes[p.symbol].value*(1-state.slippagePct/100);eq+=val;pnl+=val*(1-state.feePct/100)-p.amount} $('equity').textContent=missing?'نامشخص':USD(eq);$('pnl').textContent=missing?'نامشخص':USD(pnl);$('pnl').style.color=missing?'var(--yellow)':pnl<0?'var(--red)':'var(--green)';$('openCount').textContent=state.positions.length;$('lastGood').textContent=lastSuccess?new Date(lastSuccess).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}):'—'}
function chart(a){let rows=a.slice(-40),lo=Math.min(...rows.map(x=>x[1])),hi=Math.max(...rows.map(x=>x[2])),range=Math.max(hi-lo,1e-12),w=320,h=128;const y=v=>116-(v-lo)/range*104;return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="نمودار کندل بسته‌شده">${rows.map((r,i)=>{const xx=7+i*7.7,c=r[4]>=r[3]?'#50dcb0':'#ff7889';return `<line x1="${xx}" x2="${xx}" y1="${y(r[1])}" y2="${y(r[2])}" stroke="${c}"/><line x1="${xx}" x2="${xx}" y1="${y(r[3])}" y2="${y(r[4])}" stroke="${c}" stroke-width="4"/>`}).join('')}</svg>`}
function render(){const search=$('search').value.trim().toUpperCase(),mode=$('mode').value,amt=Math.max(5,Number($('scenarioAmt').value)||20);let arr=Object.entries(markets).map(([s,m])=>[s,m,choose(m)]).filter(([s])=>!search||s.includes(search));if(mode==='selected'&&!search)arr=arr.filter(x=>x[2]).sort((a,b)=>b[2].score-a[2].score||a[2].atrPct-b[2].atrPct).slice(0,25);else if(mode==='wait')arr=arr.filter(x=>!x[2]);else arr=arr.sort((a,b)=>(b[2]?.score??-100)-(a[2]?.score??-100)).slice(0,search?100:25);const root=$('cards');root.innerHTML='';if(!arr.length){root.innerHTML='<div class="empty">در این اسکن هیچ فرصت دارای شرایط کافی و نسبت سود به ضرر خالص حداقل ۱٫۵ یافت نشد. «همه بازارهای بررسی‌شده» را برای مشاهده صبر انتخاب کن.</div>';return}for(const [s,m,b] of arr){const analysis=b||m.periods?.[900]||Object.values(m.periods||{})[0];if(!analysis)continue;const ok=!!b,hold=PERIODS.find(x=>x.sec===b?.sec),sc=ok?scenario(amt,b.price,b.stopPct,b.takePct):null;const status=ok?'بررسی خرید آزمایشی':analysis.status==='AVOID'?'اجتناب از خرید':'صبر / شواهد کافی نیست';const card=document.createElement('div');card.className='coin';card.innerHTML=`<div class="top"><h3>${s}</h3><div class="price">${price(analysis.price)}</div></div><div class="statsrow"><div>امتیاز<b>${analysis.score}</b></div><div>RSI<b>${num(analysis.rsi,1)}</b></div><div>ATR %<b>${num(analysis.atrPct,2)}</b></div><div>حجم نسبی<b>×${num(analysis.vr,1)}</b></div></div>${chart(analysis.candles)}<div class="detail"><strong class="${ok?'buy':analysis.status==='AVOID'?'avoid':'wait'}">${status}</strong><div class="detailgrid"><div><small>جهت</small>${ok?'خرید Long':'فعلاً معامله نکن'}</div><div><small>مدت تحلیل‌شده</small>${hold?hold.label:'تأیید نشده'}</div><div><small>قیمت مرجع ورود (کندل بسته)</small>${price(analysis.price)}</div><div><small>سطح ریسک</small>${analysis.risk}</div><div><small>نسبت سود به ضرر خالص</small>${ok?num(quality(b,20)?.rr,2)+' به ۱':'تأیید نشده'}</div><div><small>هدف سود نمونه</small>${ok?price(b.price*(1+b.takePct/100)):'—'}</div><div><small>حد ضرر نمونه</small>${ok?price(b.price*(1-b.stopPct/100)):'—'}</div><div><small>سود سناریوی ${USD(amt)}</small>${ok?USD(sc.up):'—'}</div><div><small>زیان سناریوی ${USD(amt)}</small>${ok?USD(sc.down):'—'}</div></div><p class="sub">${analysis.reasons.join(' • ')}</p><p class="sub">${ok?'فیلتر سود/ضرر خالص حداقل ۱٫۵ به ۱؛ بر پایه کندل‌های بسته‌شده. این مدت تضمین رسیدن به سود نیست.':'این نماد در بازه‌های بررسی‌شده، معیارهای لازم برای پیشنهاد خرید را نداشته است.'}</p></div><button class="paper" data-symbol="${s}">خرید آزمایشی / جزئیات</button>`;root.appendChild(card)}root.querySelectorAll('.paper').forEach(b=>b.onclick=()=>openTrade(b.dataset.symbol))}
async function discover(){try{const ps=await req(API+'/products',1);products=ps.filter(p=>p.quote_currency==='USD'&&p.status==='online'&&!p.trading_disabled&&!p.cancel_only&&!p.limit_only&&/^[A-Z0-9]+-USD$/.test(p.id));const sorted=[...products].sort((a,b)=>(Number(b.volume_24h)||0)-(Number(a.volume_24h)||0)).map(p=>p.id);return [...new Set(['BTC-USD','ETH-USD','SOL-USD','XRP-USD','ADA-USD','DOGE-USD','LINK-USD',...sorted])].slice(0,MAX)}catch{if(!navigator.onLine)throw Error('اینترنت قطع است');throw Error('دریافت فهرست بازارها ناموفق بود')}}
async function pooled(items,fn,n=3){let i=0;await Promise.all(Array.from({length:n},async()=>{while(i<items.length){const item=items[i++];await fn(item)}}))}
async function scan(){if(busy)return;busy=true;lastAttempt=Date.now();$('scan').disabled=$('refresh').disabled=true;$('status').textContent='اسکن در جریان…';$('scanInfo').textContent='مرحله ۱: دریافت و اعتبارسنجی اطلاعات بازار';let success=0,errors={};const bad=e=>{let k=e?.message||'نامعلوم';errors[k]=(errors[k]||0)+1};try{const symbols=await discover(),next={};await pooled(symbols,async s=>{try{let a=analyze(await candles(s,900),900);next[s]={periods:{900:a}};success++}catch(e){bad(e)}},3);if(success===0)throw Error('هیچ داده معتبر دریافت نشد');const shortlist=Object.entries(next).sort((a,b)=>b[1].periods[900].score-a[1].periods[900].score).slice(0,Math.min(35,success)).map(x=>x[0]);$('scanInfo').textContent=`مرحله ۲: تحلیل چندبازه‌ای ${shortlist.length} بازار منتخب`;await pooled(shortlist,async s=>{for(const sec of [300,3600]){try{next[s].periods[sec]=analyze(await candles(s,sec),sec)}catch(e){bad(e)}}},3);const extra=shortlist.slice(0,15);await pooled(extra,async s=>{for(const sec of [60,86400]){try{next[s].periods[sec]=analyze(await candles(s,sec),sec)}catch(e){bad(e)}}},3);markets=next;lastSuccess=Date.now();state.mode='live';save();const choices=Object.values(markets).filter(x=>choose(x)).length;$('status').textContent='آخرین اسکن موفق: '+new Date(lastSuccess).toLocaleTimeString('fa-IR');$('scanInfo').textContent=`${success} بازار معتبر از ${symbols.length} بازار؛ ${choices} نماد دارای سیگنال و نسبت سود به ضرر خالص حداقل ۱٫۵؛ نمایش حداکثر ۲۵ مورد. ${Object.entries(errors).map(([k,v])=>k+': '+v).slice(0,4).join(' | ')}. این اسکن تحلیل محلی و غیرتضمینی است.`;render();await refreshPositions()}catch(e){state.mode='offline';save();$('status').textContent='تلاش ناموفق: '+new Date(lastAttempt).toLocaleTimeString('fa-IR');$('scanInfo').textContent='اسکن ناموفق: '+e.message+'؛ آخرین اسکن موفق: '+(lastSuccess?date(lastSuccess):'نداریم');markets={};render()}finally{busy=false;$('scan').disabled=$('refresh').disabled=false;portfolio()}}
async function direct(){const s=cleanSymbol($('search').value);if(!s){toast('نماد معتبر وارد کن');return}try{const periods={};for(const sec of [900,300,3600]){try{periods[sec]=analyze(await candles(s,sec),sec)}catch{}}if(!Object.keys(periods).length)throw Error('کندل معتبر پیدا نشد');markets[s]={periods};render();toast(s+' بررسی شد')}catch(e){toast('جست‌وجو ناموفق: '+e.message)}}
function openTrade(s){const m=markets[s],b=choose(m);selected=s;$('dialogSymbol').textContent=s;$('dialogSignal').textContent=b?'فرصت الگوریتمی با نسبت سود/ضرر خالص ≥ ۱٫۵: '+PERIODS.find(x=>x.sec===b.sec).label:'بدون تأیید خرید؛ فقط برای آزمایش نرم‌افزار';$('amount').value=20;$('sl').value=num(b?.stopPct||1.5,2);$('tp').value=num(b?.takePct||2.5,2);$('hold').value=String(b?.hold||14400);$('tradeError').textContent='';$('dialog').showModal();preview()}
function preview(){const a=Number($('amount').value),sl=Number($('sl').value),tp=Number($('tp').value),m=markets[selected],b=choose(m)||m?.periods?.[900];if(!b)return;const r=scenario(a,b.price,sl,tp);if(!r||!Number.isFinite(r.up)||!Number.isFinite(r.down)){$('preview').textContent='مبلغ یا درصدها نامعتبرند';return}$('preview').textContent=`برای ${USD(a)}: در هدف سود ${USD(r.up)}؛ در حد ضرر ${USD(r.down)} (هزینه‌های فرضی منظور شده). زمان بررسی خروج: ${date(Date.now()+Number($('hold').value)*1000)}. قیمت ورود نهایی تازه دریافت می‌شود.`}
async function buy(){const a=Number($('amount').value),sl=Number($('sl').value),tp=Number($('tp').value),hold=Number($('hold').value);const error=msg=>{$('tradeError').textContent=msg;toast(msg)};if(!Number.isFinite(a)||a<5||a>state.maxTrade||a>state.cash)return error('مبلغ باید حداقل ۵ دلار و کمتر از سقف معامله و موجودی باشد');if(!Number.isFinite(sl)||sl<.2||sl>80||!Number.isFinite(tp)||tp<.2||tp>300)return error('حد سود یا ضرر نامعتبر است');if(![300,1200,14400,86400,2592000].includes(hold))return error('مدت نامعتبر');if(state.positions.some(p=>p.symbol===selected))return error('برای این ارز معامله باز وجود دارد');$('buy').disabled=true;try{const q=await quote(selected),entry=q.value*(1+state.slippagePct/100),qty=a*(1-state.feePct/100)/entry,now=Date.now();state.cash-=a;state.positions.push({id:now+'-'+Math.random().toString(36).slice(2),symbol:selected,amount:a,qty,entry,stop:entry*(1-sl/100),take:entry*(1+tp/100),openedAt:now,expiresAt:now+hold*1000,holdMs:hold*1000,exitOnTrend:$('trendExit').checked,period:choose(markets[selected])?.sec||900});save();positions();$('dialog').close();toast('خرید ۱۰۰٪ مجازی انجام شد')}catch(e){error('خرید انجام نشد: '+e.message)}finally{$('buy').disabled=false}}
async function close(id,reason='Manual',trigger=null){if(closing.has(id))return;closing.add(id);try{const p=state.positions.find(x=>x.id===id);if(!p)return;const q=await quote(p.symbol);const exit=q.value*(1-state.slippagePct/100),net=p.qty*exit*(1-state.feePct/100),pnl=net-p.amount;state.cash+=net;state.positions=state.positions.filter(x=>x.id!==id);state.history.unshift({...p,exit,exitMarketPrice:q.value,closedAt:Date.now(),pnl,why:reason,triggerPrice:trigger?.price??null,triggerAt:trigger?.at??null,delayMs:p.expiresAt?Math.max(0,Date.now()-p.expiresAt):null});save();positions();history();toast('خروج مجازی: '+USD(pnl))}catch(e){toast('معامله باز ماند؛ قیمت تازه دریافت نشد: '+e.message)}finally{closing.delete(id)}}
async function refreshPositions(){const symbols=[...new Set(state.positions.map(p=>p.symbol))];await pooled(symbols,async s=>{try{await quote(s)}catch{delete quotes[s]}},3);for(const p of [...state.positions]){if(!quoteOK(p.symbol))continue;const q=quotes[p.symbol];let reason='';if(q.value<=p.stop)reason='Stop Loss';else if(q.value>=p.take)reason='Take Profit';else if(Number.isFinite(p.expiresAt)&&Date.now()>=p.expiresAt)reason='Time Limit (checked late)';else if(p.exitOnTrend&&markets[p.symbol]?.periods?.[p.period]?.status==='AVOID')reason='Trend Weakened';if(reason)await close(p.id,reason,{price:q.value,at:q.received})}positions();portfolio()}
function positions(){const el=$('positionCards');el.innerHTML='';if(!state.positions.length){el.innerHTML='<div class="empty">معامله بازی وجود ندارد.</div>';portfolio();return}for(const p of state.positions){const ok=quoteOK(p.symbol),last=ok?quotes[p.symbol].value:NaN,pnl=ok?p.qty*last*(1-state.slippagePct/100)*(1-state.feePct/100)-p.amount:NaN;const item=document.createElement('div');item.className='coin';item.innerHTML=`<div class="top"><h3>${p.symbol}</h3><b class="${ok?(pnl<0?'avoid':'buy'):'wait'}">${ok?USD(pnl):'قیمت تازه موجود نیست'}</b></div><div class="detailgrid"><div><small>قیمت ورود</small>${price(p.entry)}</div><div><small>قیمت تازه</small>${price(last)}</div><div><small>حد سود</small>${price(p.take)}</div><div><small>حد ضرر</small>${price(p.stop)}</div><div><small>شروع</small>${date(p.openedAt)}</div><div><small>مهلت بررسی خروج</small>${date(p.expiresAt)}</div></div><p class="sub">آخرین قیمت: ${ok?date(quotes[p.symbol].received):'نامعتبر'}؛ نظارت فقط هنگام باز بودن و دریافت قیمت تازه</p><button class="danger close" data-id="${p.id}">بستن دستی با قیمت تازه</button>`;el.appendChild(item)}el.querySelectorAll('.close').forEach(b=>b.onclick=()=>close(b.dataset.id));portfolio()}
function history(){const el=$('historyCards');el.innerHTML='';if(!state.history.length){el.innerHTML='<div class="empty">هنوز معامله بسته‌شده‌ای وجود ندارد.</div>';return}for(const h of state.history.slice(0,100)){const el2=document.createElement('div');el2.className='coin';el2.innerHTML=`<div class="top"><h3>${h.symbol}</h3><strong class="${h.pnl<0?'avoid':'buy'}">${USD(h.pnl)}</strong></div><div class="detailgrid"><div><small>دلیل</small>${String(h.why||'—').replace(/[<>]/g,'')}</div><div><small>زمان خروج</small>${date(h.closedAt)}</div><div><small>ورود</small>${price(h.entry)}</div><div><small>قیمت خروج ثبت‌شده</small>${price(h.exit)}</div><div><small>قیمت فعال‌کننده خروج</small>${h.triggerPrice==null?'ثبت نشده':price(h.triggerPrice)}</div><div><small>تأخیر مهلت</small>${h.delayMs==null?'نامشخص':Math.round(h.delayMs/60000)+' دقیقه'}</div></div>`;el.appendChild(el2)}}
function wire(){for(const id of ['scan','refresh'])$(id).onclick=scan;$('direct').onclick=direct;$('mode').onchange=render;$('search').oninput=render;$('scenarioAmt').oninput=render;$('refreshOpen').onclick=refreshPositions;$('dismiss').onclick=()=>$('dialog').close();for(const id of ['amount','sl','tp','hold'])$(id).addEventListener('input',preview);$('buy').onclick=buy;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.target).classList.add('active');positions();history()});for(const key of ['maxTrade','feePct','slippagePct'])$(key).value=state[key];$('saveSettings').onclick=()=>{const m=Number($('maxTrade').value),f=Number($('feePct').value),s=Number($('slippagePct').value);if(![m,f,s].every(Number.isFinite)||m<5||m>100000||f<0||f>5||s<0||s>5){toast('تنظیمات نامعتبر');return}Object.assign(state,{maxTrade:m,feePct:f,slippagePct:s});save();toast('تنظیمات ذخیره شد')};$('backup').onclick=()=>{const data=JSON.stringify({format:'SunnyTradeBackup',version:8,createdAt:new Date().toISOString(),data:state},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='sunny-trade-backup-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)};$('restore').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2e6)throw Error('فایل بزرگ');const b=JSON.parse(await f.text()),d=b.data;if(b.format!=='SunnyTradeBackup'||!d||!Array.isArray(d.positions)||!Array.isArray(d.history)||!Number.isFinite(d.cash)||d.cash<0||d.positions.length>500||d.history.length>100000||d.positions.some(p=>!p||!cleanSymbol(p.symbol)||!Number.isFinite(p.qty)||p.qty<=0||!Number.isFinite(p.amount)||p.amount<=0))throw Error('ساختار نامعتبر');if(!confirm('اطلاعات فعلی با پشتیبان جایگزین شود؟'))return;state={...DEFAULT(),...d};quotes={};save();positions();history();toast('بازیابی شد')}catch(err){toast('بازیابی ناموفق: '+err.message)}finally{e.target.value=''}};$('reset').onclick=()=>{if(confirm('تمام سرمایه، معاملات و تاریخچه مجازی پاک شود؟')){state={...DEFAULT(),maxTrade:state.maxTrade,feePct:state.feePct,slippagePct:state.slippagePct};quotes={};save();positions();history()}};document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshPositions();if(Date.now()-lastSuccess>15*60000)scan()}})}
wire();positions();history();portfolio();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));scan();
