/* Sunny Trade AI v0.3 — browser-only paper trading. No live trading or AI model. */
'use strict';
const API='https://api.exchange.coinbase.com', KEY='sunnyTradeMobileV02', COUNT=40;
const SEED=['BTC-USD','ETH-USD','SOL-USD','XRP-USD','ADA-USD','DOGE-USD','LINK-USD','AVAX-USD'];
const $=id=>document.getElementById(id), money=x=>Number(x||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}),fmt=(x,n=2)=>Number(x).toLocaleString('en-US',{maximumFractionDigits:n});
const defaults=()=>({cash:1000,startingBalance:1000,maxTrade:100,feePct:0.1,slippagePct:0.05,positions:[],history:[],mode:'offline'});
let state;try{state={...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state=defaults()}
if(!Array.isArray(state.positions))state.positions=[];if(!Array.isArray(state.history))state.history=[];
let markets={},selectedSymbols=SEED.slice(),busy=false,scanAt=0;
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));updatePortfolio()};
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function emaLast(x,n){if(x.length<n+30)return NaN;let v=x.slice(0,n).reduce((a,b)=>a+b,0)/n;for(let i=n;i<x.length;i++)v=v+(2/(n+1))*(x[i]-v);return v}
function rsi(x,n=14){if(x.length<n+2)return NaN;let gain=0,loss=0;for(let i=1;i<=n;i++){let d=x[i]-x[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}gain/=n;loss/=n;for(let i=n+1;i<x.length;i++){let d=x[i]-x[i-1];gain=(gain*(n-1)+Math.max(d,0))/n;loss=(loss*(n-1)+Math.max(-d,0))/n}return loss===0?(gain===0?50:100):100-100/(1+gain/loss)}
function atr(a,n=14){if(a.length<n+1)return NaN;let tr=[];for(let i=1;i<a.length;i++){let p=a[i-1][4];tr.push(Math.max(a[i][2]-a[i][1],Math.abs(a[i][2]-p),Math.abs(a[i][1]-p)))}let t=tr.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<tr.length;i++)t=(t*(n-1)+tr[i])/n;return t}
function analyze(rows){const x=rows.map(r=>r[4]),n=x.length,p=x[n-1],e20=emaLast(x,20),e50=emaLast(x,50),macd=emaLast(x,12)-emaLast(x,26),rr=rsi(x),ap=atr(rows)/p*100;
const v=rows.map(r=>r[5]),avg=v.slice(-21,-1).reduce((a,b)=>a+b,0)/20,vr=avg>0?v.at(-1)/avg:NaN;let score=0,reasons=[];
if(p>e20){score++;reasons.push('قیمت بالای EMA20')}else{score--;reasons.push('قیمت زیر EMA20')}
if(e20>e50){score++;reasons.push('روند میان‌مدت صعودی')}else{score--;reasons.push('روند میان‌مدت نزولی')}
if(rr>=45&&rr<=68){score++;reasons.push('RSI متعادل')}else if(rr>75){score-=2;reasons.push('RSI بسیار بالا')}else if(rr<35){score--;reasons.push('RSI ضعیف')}
if(macd>0)score++;else score--;
if(vr>1.15){score++;reasons.push('حجم بالاتر از میانگین')}
if(ap>6){score--;reasons.push('نوسان بالا')}
const signal=score>=3?'BUY':score<=-2?'AVOID':'WAIT';const risk=ap>5?'نوسان زیاد':ap>2?'نوسان متوسط':'نوسان کمتر';
return {price:p,change:(p/x[n-2]-1)*100,rsi:rr,ema20:e20,ema50:e50,macd,atrPct:ap,volRatio:vr,score,signal,risk,reasons,entry:p,stop:p-1.5*atr(rows),take:p+2.25*atr(rows)} }
function request(url){return fetch(url,{cache:'no-store',headers:{Accept:'application/json'}}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()})}
async function discover(){try{const list=await request(API+'/products');const good=list.filter(p=>p.quote_currency==='USD'&&p.status==='online'&&!p.trading_disabled&&!p.cancel_only&&!p.limit_only&&p.id&&/^[A-Z0-9]+-USD$/.test(p.id));
const byVolume=good.sort((a,b)=>(Number(b.volume_24h)||0)-(Number(a.volume_24h)||0));const ids=[...new Set([...SEED,...byVolume.map(x=>x.id)])];return ids.slice(0,COUNT)}catch{return SEED.slice()}}
async function candles(symbol,granularity){let raw=await request(`${API}/products/${encodeURIComponent(symbol)}/candles?granularity=${granularity}`);if(!Array.isArray(raw)||raw.length<100)throw Error('داده کافی نیست');const end=Math.floor(Date.now()/1000/granularity)*granularity;return raw.filter(r=>Array.isArray(r)&&r.length>=6&&r.every((v,i)=>i<6?Number.isFinite(+v):true)&&+r[0]<end).sort((a,b)=>a[0]-b[0]).map(r=>r.slice(0,6).map(Number)).filter(r=>r[4]>0&&r[2]>=r[1]).slice(-280)}
async function scan(){if(busy)return;busy=true;scanAt=0;$('scanBtn').disabled=true;$('refreshBtn').disabled=true;let period=Number($('interval').value);$('statusLine').textContent='در حال دریافت داده…';$('scannerInfo').textContent='ابتدا فهرست بازارها و سپس کندل‌ها دریافت می‌شوند. ممکن است حدود یک دقیقه طول بکشد.';
const ids=await discover();selectedSymbols=ids;let result={},fail=0,next=0;
async function worker(){while(next<ids.length){let i=next++,symbol=ids[i];try{let cs=await candles(symbol,period);if(cs.length<85)throw Error('ناکافی');result[symbol]={...analyze(cs),candles:cs,updated:Date.now(),period,live:true}}catch{fail++}}}
await Promise.all(Array.from({length:4},worker));markets=result;scanAt=Date.now();state.mode=Object.keys(markets).length?'live':'offline';save();busy=false;$('scanBtn').disabled=false;$('refreshBtn').disabled=false;
$('statusLine').textContent=`آخرین اسکن: ${new Date(scanAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}`;$('scannerInfo').textContent=`${Object.keys(markets).length} بازار با کندل واقعی و بسته‌شده؛ ${fail} بازار بدون داده کافی. مرتب‌سازی بر اساس امتیاز اولیه است، نه احتمال تضمین‌شده سود.`;
renderMarkets();renderPositions();checkStops()}
function chart(a){if(!a||!a.length)return '';const w=310,h=125,b=12,max=Math.max(...a.map(r=>r[2])),min=Math.min(...a.map(r=>r[1])),range=Math.max(1e-9,max-min),y=v=>h-b-(v-min)/range*(h-2*b),bw=(w-2*b)/a.length;let items=a.map((r,i)=>{const x=b+i*bw+bw/2,c=r[4]>=r[3]?'#50cba5':'#ee8090';return `<line x1="${x.toFixed(1)}" x2="${x.toFixed(1)}" y1="${y(r[2]).toFixed(1)}" y2="${y(r[1]).toFixed(1)}" stroke="${c}" stroke-width="1"/><line x1="${x.toFixed(1)}" x2="${x.toFixed(1)}" y1="${y(r[3]).toFixed(1)}" y2="${y(r[4]).toFixed(1)}" stroke="${c}" stroke-width="${Math.max(1.5,bw*.6).toFixed(1)}"/>`}).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="نمودار شمعی آخرین کندل‌های بسته‌شده">${items}</svg>`}
function renderMarkets(){const grid=$('marketGrid'),search=$('marketSearch').value.trim().toUpperCase(),filter=$('riskFilter').value;grid.innerHTML='';let list=Object.entries(markets).filter(([s,a])=>s.includes(search)&&(filter==='all'||(filter==='candidate'&&a.signal==='BUY')||(filter==='wait'&&a.signal==='WAIT')||(filter==='avoid'&&a.signal==='AVOID'))).sort((a,b)=>b[1].score-a[1].score||a[1].atrPct-b[1].atrPct);
if(!list.length){grid.innerHTML='<div class="empty">برای این فیلتر نتیجه‌ای با داده معتبر موجود نیست.</div>';return}
for(const [s,a] of list){const type=a.signal==='BUY'?['بررسی خرید','signal-buy']:a.signal==='WAIT'?['صبر','signal-wait']:['سیگنال خرید ضعیف','signal-avoid'];const card=document.createElement('article');card.className='market card';card.innerHTML=`<div class="market-head"><div><div class="symbol">${s}</div><div class="small">داده عمومی • کندل بسته‌شده</div></div><div><div class="price">${money(a.price)}</div><div class="change ${a.change>=0?'good':'bad'}">${a.change>=0?'+':''}${fmt(a.change)}%</div></div></div><div class="metrics"><div class="metric"><span>RSI</span><b>${fmt(a.rsi,1)}</b></div><div class="metric"><span>ATR%</span><b>${fmt(a.atrPct,2)}</b></div><div class="metric"><span>Volume</span><b>×${fmt(a.volRatio,1)}</b></div><div class="metric"><span>Score</span><b>${a.score}</b></div></div><div class="mini-chart">${chart(a.candles.slice(-45))}</div><div class="signal"><span class="signal-badge ${type[1]}">${type[0]}</span><button class="secondary trade-open" data-symbol="${s}">Paper Buy</button></div><p class="reason">${a.reasons.slice(0,4).join(' • ')}<br>نوسان: ${a.risk} • هدف و حد ضرر صرفاً نمونه ATR هستند</p>`;grid.appendChild(card)}
document.querySelectorAll('.trade-open').forEach(b=>b.onclick=()=>openTrade(b.dataset.symbol))}
function scenario(amount,price,stopPct,takePct){
 const fee=state.feePct/100, slip=state.slippagePct/100;
 if(![amount,price,stopPct,takePct,fee,slip].every(Number.isFinite)||amount<=0||price<=0||stopPct<=0||takePct<=0)return null;
 const entry=price*(1+slip), qty=amount*(1-fee)/entry;
 const project=target=>qty*target*(1-slip)*(1-fee);
 const gain=project(entry*(1+takePct/100)), loss=project(entry*(1-stopPct/100));
 return {gain,loss,profit:gain-amount,down:loss-amount};
}
function updateDollarPreview(){const amount=Number($('tradeAmount').value),stop=Number($('stopPct').value),take=Number($('takePct').value),a=markets[$('tradeSymbol').textContent],d=$('dollarPreview');if(!a||!fresh(a)){d.textContent='برای محاسبه ابتدا داده بازار را تازه‌سازی کن.';return}const r=scenario(amount,a.price,stop,take);if(!r){d.textContent='مبلغ و حد سود و حد ضرر معتبر وارد کن.';return}
 d.innerHTML=`<strong>نتیجه احتمالی با ${money(amount)} سرمایه مجازی</strong><br><span class="good">اگر قیمت به هدف سود برسد:</span> دارایی شما تقریباً ${money(r.gain)} می‌شود؛ ${r.profit>=0?'سود':'زیان'} خالص <b>${money(Math.abs(r.profit))}</b>.<br><span class="bad">اگر قیمت به حد ضرر برسد:</span> دارایی شما تقریباً ${money(r.loss)} می‌شود؛ ${r.down<0?'زیان':'سود'} خالص <b>${money(Math.abs(r.down))}</b>.<br><small>محاسبه نمونه با کارمزد رفت‌وبرگشت و لغزش فرضی است؛ اجرای واقعی و قیمت خروج تضمین‌شده نیست. این اعداد احتمال موفقیت را نشان نمی‌دهند.</small>`;
}
function openTrade(symbol){const a=markets[symbol];if(!a)return;$('tradeSymbol').textContent=symbol;$('tradeAmount').value=Math.min(20,state.maxTrade);$('tradeSummary').innerHTML=`قیمت داده بسته‌شده: ${money(a.price)}<br>RSI ${fmt(a.rsi,1)} • Score ${a.score} • ${a.risk}<br>حد ضرر ATR پیشنهادی: ${money(a.stop)} | هدف ATR: ${money(a.take)}<br>این قیمت قطعی اجرای سفارش نیست.`;$('tradeChart').innerHTML=chart(a.candles.slice(-55));$('tradeDialog').showModal();updateDollarPreview()}
function fresh(a){return a&&a.live&&scanAt&&Date.now()-scanAt<15*60*1000}
function paperBuy(){const symbol=$('tradeSymbol').textContent,a=markets[symbol],amount=Number($('tradeAmount').value),sl=Number($('stopPct').value),tp=Number($('takePct').value);
if(!fresh(a)){toast('داده قدیمی است؛ ابتدا بازار را تازه اسکن کن');return false}if(!Number.isFinite(amount)||amount<5||amount>state.cash||amount>state.maxTrade||!Number.isFinite(sl)||sl<.2||sl>80||!Number.isFinite(tp)||tp<.2||tp>300){toast('مبلغ یا حد سود/ضرر معتبر نیست');return false}if(state.positions.some(p=>p.symbol===symbol)){toast('برای این ارز معامله باز وجود دارد');return false}
const entry=a.price*(1+state.slippagePct/100),qty=amount*(1-state.feePct/100)/entry;state.cash-=amount;state.positions.push({id:String(Date.now())+Math.random(),symbol,amount,qty,entry,stop:entry*(1-sl/100),take:entry*(1+tp/100),openedAt:Date.now(),sourceLive:true});save();renderPositions();toast('خرید فقط با پول مجازی انجام شد');return true}
function closePosition(id,why='Manual'){const p=state.positions.find(x=>x.id===id);if(!p)return;const a=markets[p.symbol];if(!fresh(a)){toast('برای خروج باید قیمت تازه دریافت شود');return}const exit=a.price*(1-state.slippagePct/100),gross=p.qty*exit,net=gross*(1-state.feePct/100),pnl=net-p.amount;state.cash+=net;state.positions=state.positions.filter(x=>x.id!==id);state.history.unshift({...p,exit,closedAt:Date.now(),pnl,why});save();renderPositions();renderHistory();toast('نتیجه مجازی: '+money(pnl))}
function checkStops(){for(const p of [...state.positions]){const a=markets[p.symbol];if(!fresh(a))continue;if(a.price<=p.stop)closePosition(p.id,'Stop Loss');else if(a.price>=p.take)closePosition(p.id,'Take Profit')}}
function renderPositions(){const root=$('positionsList');root.innerHTML=state.positions.length?'':'<div class="empty">هیچ معامله آزمایشی بازی نداری.</div>';for(const p of state.positions){const a=markets[p.symbol],price=a?.price||p.entry,pnl=p.qty*price*(1-state.slippagePct/100)*(1-state.feePct/100)-p.amount,d=document.createElement('div');d.className='position card';d.innerHTML=`<div class="row"><div class="symbol">${p.symbol}</div><div class="pnl ${pnl>=0?'good':'bad'}">${money(pnl)}</div></div><div class="metrics"><div class="metric"><span>SL</span><b>${money(p.stop)}</b></div><div class="metric"><span>TP</span><b>${money(p.take)}</b></div><div class="metric"><span>ورود</span><b>${money(p.entry)}</b></div><div class="metric"><span>قیمت آخر</span><b>${money(price)}</b></div></div><p class="small">حد سود/ضرر فقط هنگام اسکن و باز بودن اپ بررسی می‌شود؛ وقتی برنامه بسته است سفارش واقعی ثبت نمی‌شود.</p><button class="danger full close-pos" data-id="${p.id}">بستن مجازی</button>`;root.appendChild(d)}document.querySelectorAll('.close-pos').forEach(b=>b.onclick=()=>closePosition(b.dataset.id))}
function renderHistory(){const root=$('historyList');root.innerHTML=state.history.length?'':'<div class="empty">هنوز معامله بسته‌شده‌ای ثبت نشده.</div>';for(const h of state.history.slice(0,100)){const d=document.createElement('div');d.className='history-item card';d.innerHTML=`<div class="row"><div><div class="symbol">${h.symbol}</div><div class="small">${h.why} • ${new Date(h.closedAt).toLocaleDateString('fa-IR')}</div></div><div class="pnl ${h.pnl>=0?'good':'bad'}">${money(h.pnl)}</div></div>`;root.appendChild(d)}}
function updatePortfolio(){let pnl=0,total=state.cash;for(const p of state.positions){const val=p.qty*(markets[p.symbol]?.price||p.entry)*(1-state.slippagePct/100);total+=val;pnl+=val*(1-state.feePct/100)-p.amount}$('equity').textContent=money(total);$('openPnl').textContent=money(pnl);$('openPnl').className='medium '+(pnl>=0?'good':'bad');$('openCount').textContent=state.positions.length;$('dataModeLabel').textContent=state.mode==='live'?'Live':'آفلاین'}
for(const id of ['tradeAmount','stopPct','takePct'])$(id).addEventListener('input',updateDollarPreview);
$('scanBtn').onclick=scan;$('refreshBtn').onclick=scan;$('interval').onchange=scan;$('riskFilter').onchange=renderMarkets;$('marketSearch').oninput=renderMarkets;
$('confirmPaperBuy').onclick=e=>{e.preventDefault();if(paperBuy())$('tradeDialog').close()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');renderPositions();renderHistory()});
$('saveSettings').onclick=()=>{let amt=Number($('startingBalance').value),max=Number($('maxTrade').value),fee=Number($('feePct').value),slip=Number($('slippagePct').value);if(!(amt>=10&&max>=5&&max<=amt&&fee>=0&&fee<=5&&slip>=0&&slip<=5)){toast('مقادیر تنظیمات نامعتبر است');return}state.startingBalance=amt;state.maxTrade=max;state.feePct=fee;state.slippagePct=slip;save();toast('تنظیمات ذخیره شد')};
$('resetPaper').onclick=()=>{if(confirm('همه معاملات و تاریخچه آزمایشی حذف شوند؟')){let keep={startingBalance:state.startingBalance,maxTrade:state.maxTrade,feePct:state.feePct,slippagePct:state.slippagePct};state={...defaults(),...keep,cash:keep.startingBalance};save();renderPositions();renderHistory()}};
for(const id of ['startingBalance','maxTrade','feePct','slippagePct'])$(id).value=state[id];
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));renderHistory();renderPositions();updatePortfolio();scan();
